### PR TITLE
PEP8

### PR DESCRIPTION
**Pull request by deepserket**
I was wondering: if you use multiprocessing the hashrate increases? ( i think yes, hoping that random.randint and SHA256 are non blocking)

BTW this project is great for learning

### CODE REVIEW

**Comment by iHateRa1n** [comment]
Thanks, I'm one of the developers. 

It might work, but from what I know when you use Threading, it only uses 1 core. I could be wrong though. 

I might test it. 

EDIT: It seems, (at least on my 2 core MBP) that it uses both cores. We'll consider the changes with some other edits.

**Review by iHateRa1n — APPROVED** [review]
It will be approved, but we are going to still change some things.

**Comment by rimcoin** [comment]
We meant to say soon. Typo.

**Comment by deepserket** [comment]
@iHateRa1n I said `multiprocessing`, because thanks to the GIL you can't do CPU-bound concurrency with multithreading

**Pull request merged**
